template:
  path: "opendata-bucket.j2"
stack_name: "darteval-bucket"
dependencies:
  - "prod/bootstrap.yaml"
parameters:
  DataSetName: "darteval.opendata.sagebase.org"
sceptre_user_data:
  SynapseIDs:
    - "3453016" # DPE team
    - "3485485" # DPE service account
