template:
  path: "opendata-bucket.j2"
stack_name: "rosmap"
dependencies:
  - "prod/bootstrap.yaml"
parameters:
  DataSetName: "rosmap.opendata.sagebase.org"
sceptre_user_data:
  SynapseIDs:
    - "3357888" # Will Poehlman
    - "3324230" # Tom Yu
