name: pre-commit

on:
  pull_request:
    branches: ['*']
  push:
    branches: ['*']

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11.2'
      - name: Install git-secrets
        run: |
          git clone --depth 1 https://github.com/awslabs/git-secrets.git /tmp/git-secrets
          sudo make -C /tmp/git-secrets install
      - uses: pre-commit/action@v3.0.1
